// <auto-generated />
namespace Timetable.Data.Migrations.Schedule
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemoveBuildingFromTimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveBuildingFromTimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201311042153355_RemoveBuildingFromTimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
