// <auto-generated />
namespace Timetable.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenamePeriodToTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamePeriodToTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201311191951223_RenamePeriodToTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
